#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/jwt_token
#    username: root
#    password: root
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
#server:
#  port: 8083
#
#
#  application:
#    name: jwt-auth-service
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: jwt-auth-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jwt_token
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8083

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    hostname: ${HOSTNAME:localhost}
#    prefer-ip-address: true
#    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
#
#logging:
#  level:
#    com.netflix.discovery: DEBUG
#    com.netflix.eureka: DEBUG
